import type { HFModelItem } from "./types";

export interface ModelPreset {
	id: string;
	label: string;
	providerPresetId: string;
	category: "latest" | "recommended" | "fast" | "local";
	tags: string[];
	description: string;
	model: HFModelItem;
}

const OPENAI_CODEX_OAUTH_BASE_URL = "https://chatgpt.com/backend-api/codex";
const OPENAI_CODEX_OAUTH_COMMENT =
	"Quick Setup defaults based on the official OpenAI model catalog and Responses API documentation: https://developers.openai.com/api/docs/models and https://developers.openai.com/api/docs, plus the OpenClaw Codex OAuth catalog: https://github.com/openclaw/openclaw/blob/main/extensions/openai/openclaw.plugin.json";

function createOpenAICodexOAuthPreset(options: {
	id: string;
	modelId: string;
	label: string;
	category: ModelPreset["category"];
	tags: string[];
	description: string;
	supportedReasoningEfforts: string[];
}): ModelPreset {
	return {
		id: options.id,
		label: options.label,
		providerPresetId: "openai",
		category: options.category,
		tags: options.tags,
		description: options.description,
		model: {
			id: options.modelId,
			configId: "openai-codex-oauth",
			displayName: `${options.label} (OAuth)`,
			_comment: OPENAI_CODEX_OAUTH_COMMENT,
			owned_by: "openai",
			authMode: "oauth",
			baseUrl: OPENAI_CODEX_OAUTH_BASE_URL,
			apiMode: "openai-responses",
			family: options.modelId,
			vision: true,
			context_length: 1050000,
			max_tokens: 128000,
			reasoning_effort: options.supportedReasoningEfforts.at(-1),
			supported_reasoning_efforts: options.supportedReasoningEfforts,
			default_reasoning_effort: options.supportedReasoningEfforts.at(-1),
			toolCalling: true,
		},
	};
}

const OPENAI_CODEX_OAUTH_PRESETS: readonly ModelPreset[] = [
	createOpenAICodexOAuthPreset({
		id: "openai-gpt-6-astra-codex-oauth",
		modelId: "gpt-6-astra",
		label: "GPT-6 Astra",
		category: "latest",
		tags: ["OpenAI", "Codex", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "GPT-6 Astra through the ChatGPT/Codex OAuth Responses route.",
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
	}),
	createOpenAICodexOAuthPreset({
		id: "openai-gpt-6-sol-codex-oauth",
		modelId: "gpt-6-sol",
		label: "GPT-6 Sol",
		category: "recommended",
		tags: ["OpenAI", "Codex", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "GPT-6 Sol through the ChatGPT/Codex OAuth Responses route.",
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
	}),
	createOpenAICodexOAuthPreset({
		id: "openai-gpt-6-luna-codex-oauth",
		modelId: "gpt-6-luna",
		label: "GPT-6 Luna",
		category: "fast",
		tags: ["OpenAI", "Codex", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "GPT-6 Luna through the ChatGPT/Codex OAuth Responses route.",
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
	}),
	createOpenAICodexOAuthPreset({
		id: "openai-gpt-5-6-sol-codex-oauth",
		modelId: "gpt-5.6-sol",
		label: "GPT-5.6 Sol",
		category: "latest",
		tags: ["OpenAI", "Codex", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "GPT-5.6 Sol through the ChatGPT/Codex OAuth Responses route.",
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
	}),
	createOpenAICodexOAuthPreset({
		id: "openai-gpt-5-6-terra-codex-oauth",
		modelId: "gpt-5.6-terra",
		label: "GPT-5.6 Terra",
		category: "recommended",
		tags: ["OpenAI", "Codex", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "GPT-5.6 Terra through the ChatGPT/Codex OAuth Responses route.",
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
	}),
	createOpenAICodexOAuthPreset({
		id: "openai-gpt-5-6-luna-codex-oauth",
		modelId: "gpt-5.6-luna",
		label: "GPT-5.6 Luna",
		category: "fast",
		tags: ["OpenAI", "Codex", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "GPT-5.6 Luna through the ChatGPT/Codex OAuth Responses route.",
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
	}),
];

export const MODEL_PRESETS: readonly ModelPreset[] = [
	...OPENAI_CODEX_OAUTH_PRESETS,
	{
		id: "xai-grok-4-7-oauth",
		label: "Grok 4.7 (OAuth)",
		providerPresetId: "xai-oauth",
		category: "latest",
		tags: ["xAI", "Grok", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "Grok 4.7 through the xAI subscription OAuth route.",
		model: {
			id: "grok-4.7",
			configId: "xai-oauth",
			displayName: "Grok 4.7 (OAuth)",
			_comment:
				"Quick Setup defaults based on the OpenClaw xAI OAuth catalog and official xAI Responses API documentation: https://github.com/openclaw/openclaw/blob/main/docs/providers/xai.md and https://docs.x.ai/developers/rest-api-reference/inference",
			owned_by: "xai",
			authMode: "oauth",
			baseUrl: "https://cli-chat-proxy.grok.com/v1",
			apiMode: "openai-responses",
			vision: true,
			context_length: 500000,
			max_tokens: 64000,
			reasoning_effort: "high",
			supports_reasoning_effort: true,
			supported_reasoning_efforts: ["low", "medium", "high", "xhigh"],
			default_reasoning_effort: "high",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "xai-grok-4-6-oauth",
		label: "Grok 4.6 (OAuth)",
		providerPresetId: "xai-oauth",
		category: "recommended",
		tags: ["xAI", "Grok", "OAuth", "Vision", "Reasoning", "Tools"],
		description: "Grok 4.6 through the xAI subscription OAuth route.",
		model: {
			id: "grok-4.6",
			configId: "xai-oauth",
			displayName: "Grok 4.6 (OAuth)",
			_comment:
				"Quick Setup defaults based on the OpenClaw xAI OAuth catalog and official xAI Responses API documentation: https://github.com/openclaw/openclaw/blob/main/docs/providers/xai.md and https://docs.x.ai/developers/rest-api-reference/inference",
			owned_by: "xai",
			authMode: "oauth",
			baseUrl: "https://cli-chat-proxy.grok.com/v1",
			apiMode: "openai-responses",
			vision: true,
			context_length: 500000,
			max_tokens: 64000,
			reasoning_effort: "high",
			supports_reasoning_effort: true,
			supported_reasoning_efforts: ["low", "medium", "high", "xhigh"],
			default_reasoning_effort: "high",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "azure-foundry-kimi-k2-6",
		label: "Kimi K2.6 (Azure Foundry)",
		providerPresetId: "azure-foundry",
		category: "latest",
		tags: ["Azure Foundry", "Kimi", "Vision", "Tools", "Cache"],
		description: "Kimi K2.6 through Azure Foundry with high reasoning and automatic model caching.",
		model: {
			id: "Kimi-K2.6",
			_comment:
				"Quick Setup defaults based on the official Azure Foundry Kimi K2.6 catalog and pricing pages: https://ai.azure.com/catalog/models/Kimi-K2.6 and https://azure.microsoft.com/en-us/pricing/details/ai-foundry-models/kimi/. Azure Foundry manages prompt caching automatically; do not send prompt_cache_key, prompt_cache_retention, or thinking.",
			configId: "azure-foundry",
			displayName: "Kimi K2.6 (Azure Foundry)",
			owned_by: "azure-foundry",
			baseUrl: "https://YOUR-RESOURCE-NAME.services.ai.azure.com/openai/v1",
			apiMode: "azure-foundry",
			vision: true,
			context_length: 262144,
			max_completion_tokens: 32768,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["none", "minimal", "low", "medium", "high"],
			default_reasoning_effort: "high",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "azure-foundry-deepseek-v4-pro",
		label: "DeepSeek V4 Pro (Azure Foundry)",
		providerPresetId: "azure-foundry",
		category: "recommended",
		tags: ["Azure Foundry", "DeepSeek", "Reasoning", "Tools", "Cache"],
		description: "DeepSeek V4 Pro through Azure Foundry with max reasoning and automatic model caching.",
		model: {
			id: "DeepSeek-V4-Pro",
			_comment:
				"Quick Setup defaults based on the official Azure Foundry DeepSeek V4 Pro catalog, tutorial, and pricing pages: https://ai.azure.com/catalog/models/DeepSeek-V4-Pro, https://learn.microsoft.com/en-us/azure/foundry/foundry-models/tutorials/get-started-deepseek-r1, and https://azure.microsoft.com/en-us/pricing/details/ai-foundry-models/deepseek/. Azure Foundry manages prompt caching automatically; do not send prompt_cache_key, prompt_cache_retention, or thinking.",
			configId: "azure-foundry",
			displayName: "DeepSeek V4 Pro (Azure Foundry)",
			owned_by: "azure-foundry",
			baseUrl: "https://YOUR-RESOURCE-NAME.services.ai.azure.com/openai/v1",
			apiMode: "azure-foundry",
			vision: false,
			context_length: 1000000,
			max_tokens: 128000,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["none", "high", "max"],
			default_reasoning_effort: "max",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "openai-gpt-5-5-responses",
		label: "GPT-5.5",
		providerPresetId: "openai",
		category: "latest",
		tags: ["OpenAI", "Responses", "Vision", "Reasoning"],
		description: "OpenAI frontier model for complex coding and professional work.",
		model: {
			id: "gpt-5.5",
			_comment:
				"Quick Setup defaults based on official OpenAI GPT-5.5 model docs: https://developers.openai.com/api/docs/models/gpt-5.5",
			displayName: "GPT-5.5",
			owned_by: "openai",
			baseUrl: "https://api.openai.com/v1",
			apiMode: "openai-responses",
			family: "gpt-5.5",
			vision: true,
			context_length: 1050000,
			max_tokens: 128000,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["none", "low", "medium", "high", "xhigh"],
			default_reasoning_effort: "high",
			toolCalling: true,
			extra: {
				reasoning: {
					summary: "detailed",
				},
			},
		},
	},
	{
		id: "openai-gpt-5-5-chat-completions",
		label: "GPT-5.5 (Chat Completions)",
		providerPresetId: "openai",
		category: "recommended",
		tags: ["OpenAI", "Chat Completions", "Vision", "Prompt Cache"],
		description: "OpenAI-compatible Chat Completions setup for GPT-5.5.",
		model: {
			id: "gpt-5.5",
			_comment:
				"Quick Setup defaults based on official OpenAI GPT-5.5 model docs: https://developers.openai.com/api/docs/models/gpt-5.5",
			configId: "chat-completions",
			displayName: "GPT-5.5 (Chat Completions)",
			owned_by: "openai",
			baseUrl: "https://api.openai.com/v1",
			apiMode: "openai",
			family: "gpt-5.5",
			vision: true,
			context_length: 1050000,
			max_completion_tokens: 128000,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["none", "low", "medium", "high", "xhigh"],
			default_reasoning_effort: "high",
			prompt_cache: {
				enabled: true,
			},
			toolCalling: true,
		},
	},
	{
		id: "anthropic-claude-opus-4-7",
		label: "Claude Opus 4.7",
		providerPresetId: "anthropic",
		category: "latest",
		tags: ["Anthropic", "Claude", "Vision", "Adaptive Thinking"],
		description: "Anthropic's high-capability Claude model for complex reasoning and agentic coding.",
		model: {
			id: "claude-opus-4-7",
			_comment:
				"Quick Setup defaults based on official Anthropic Claude model docs: https://platform.claude.com/docs/en/about-claude/models/overview",
			displayName: "Claude Opus 4.7",
			owned_by: "anthropic",
			baseUrl: "https://api.anthropic.com",
			apiMode: "anthropic",
			family: "claude-opus-4.7",
			vision: true,
			context_length: 1000000,
			max_tokens: 128000,
			toolCalling: true,
			supports_reasoning_effort: true,
			supported_reasoning_efforts: ["low", "medium", "high", "xhigh", "max"],
			default_reasoning_effort: "high",
			reasoning_effort: "high",
			thinking: {
				type: "adaptive",
			},
			prompt_cache: {
				enabled: true,
				anthropic: {
					enabled: true,
					cache_system: true,
					cache_tools: true,
				},
			},
		},
	},
	{
		id: "anthropic-claude-sonnet-4-6",
		label: "Claude Sonnet 4.6",
		providerPresetId: "anthropic",
		category: "recommended",
		tags: ["Anthropic", "Claude", "Vision", "Adaptive Thinking"],
		description: "Balanced Claude setup for coding, agent workflows, and daily production use.",
		model: {
			id: "claude-sonnet-4-6",
			_comment:
				"Quick Setup defaults based on official Anthropic Claude model docs: https://platform.claude.com/docs/en/about-claude/models/overview",
			displayName: "Claude Sonnet 4.6",
			owned_by: "anthropic",
			baseUrl: "https://api.anthropic.com",
			apiMode: "anthropic",
			family: "claude-sonnet-4.6",
			vision: true,
			context_length: 1000000,
			max_tokens: 64000,
			toolCalling: true,
			supports_reasoning_effort: true,
			supported_reasoning_efforts: ["low", "medium", "high", "max"],
			default_reasoning_effort: "medium",
			reasoning_effort: "medium",
			thinking: {
				type: "adaptive",
			},
			prompt_cache: {
				enabled: true,
				anthropic: {
					enabled: true,
					cache_system: true,
					cache_tools: true,
				},
			},
		},
	},
	{
		id: "deepseek-v4-pro",
		label: "DeepSeek V4 Pro",
		providerPresetId: "deepseek",
		category: "recommended",
		tags: ["DeepSeek", "Reasoning", "Tools"],
		description: "DeepSeek V4 Pro with thinking mode enabled for agentic coding workflows.",
		model: {
			id: "deepseek-v4-pro",
			_comment:
				"Quick Setup defaults based on official DeepSeek V4 model and Thinking Mode docs: https://api-docs.deepseek.com/quick_start/pricing and https://api-docs.deepseek.com/guides/thinking_mode; OAIProxy selects max reasoning effort by default.",
			displayName: "DeepSeek V4 Pro",
			owned_by: "deepseek",
			baseUrl: "https://api.deepseek.com",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_tokens: 65536,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "deepseek-flash",
		label: "DeepSeek Flash",
		providerPresetId: "deepseek",
		category: "fast",
		tags: ["DeepSeek", "Fast", "Vision", "Reasoning", "Tools"],
		description: "DeepSeek V4.1 Flash with vision, thinking, and tools through the OpenAI-compatible endpoint.",
		model: {
			id: "deepseek-flash",
			_comment:
				"Quick Setup defaults verified against official DeepSeek Flash docs on 2026-09-10: https://api-docs.deepseek.com/quick_start/pricing, https://api-docs.deepseek.com/api/create-chat-completion, https://api-docs.deepseek.com/guides/thinking_mode, and https://api-docs.deepseek.com/guides/vision; OAIProxy selects max reasoning effort and the 384K output limit. Prompt caching is provider-managed.",
			displayName: "DeepSeek Flash",
			owned_by: "deepseek",
			baseUrl: "https://api.deepseek.com",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_tokens: 393216,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "zai-glm-5-3",
		label: "GLM-5.3",
		providerPresetId: "zai",
		category: "latest",
		tags: ["Z.AI", "GLM", "Coding", "Thinking", "Tools"],
		description: "Coding model with 1M context and thinking.",
		model: {
			id: "glm-5.3",
			_comment:
				"Quick Setup defaults based on official Z.AI GLM-5.3, GLM Coding Plan, and Chat Completions docs: https://docs.z.ai/guides/llm/glm-5.3, https://docs.z.ai/devpack/latest-model, and https://docs.z.ai/api-reference/llm/chat-completion. Thinking is mandatory; context caching is provider-managed.",
			displayName: "GLM-5.3",
			owned_by: "zai",
			baseUrl: "https://api.z.ai/api/coding/paas/v4",
			apiMode: "openai",
			vision: false,
			context_length: 1000000,
			max_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
				clear_thinking: false,
			},
			temperature: 1,
			top_p: 0.95,
			extra: {
				tool_stream: true,
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "zai-glm-5-3-flash",
		label: "GLM-5.3-Flash",
		providerPresetId: "zai",
		category: "fast",
		tags: ["Z.AI", "GLM", "Fast", "Vision", "Thinking", "Tools"],
		description: "Fast multimodal model with 1M context.",
		model: {
			id: "glm-5.3-flash",
			_comment:
				"Quick Setup defaults based on official Z.AI GLM-5.3-Flash, GLM Coding Plan, and Chat Completions docs: https://docs.z.ai/guides/vlm/glm-5.3-flash, https://docs.z.ai/devpack/latest-model, and https://docs.z.ai/api-reference/llm/chat-completion. Thinking is mandatory; context caching is provider-managed.",
			displayName: "GLM-5.3-Flash",
			owned_by: "zai",
			baseUrl: "https://api.z.ai/api/coding/paas/v4",
			apiMode: "openai",
			vision: true,
			context_length: 1000000,
			max_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
				clear_thinking: false,
			},
			temperature: 1,
			top_p: 0.95,
			extra: {
				tool_stream: true,
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "kimi-k3",
		label: "Kimi K3",
		providerPresetId: "kimi",
		category: "latest",
		tags: ["Kimi", "Code", "Vision", "Thinking", "Tools", "Prompt Cache"],
		description: "Kimi's flagship 1M-context model for long-horizon coding, knowledge work, and deep reasoning.",
		model: {
			id: "kimi-k3",
			_comment:
				"Quick Setup defaults based on official Kimi K3 docs: https://platform.kimi.ai/docs/guide/kimi-k3-quickstart. K3 uses a 1M-token context and an official 131,072-token default completion allowance; max_completion_tokens can be raised up to 1,048,576 within the context window.",
			displayName: "Kimi K3",
			owned_by: "kimi",
			baseUrl: "https://api.moonshot.ai/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["max"],
			default_reasoning_effort: "max",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "tokenrouter-deepseek-v4-pro-0813",
		label: "DeepSeek V4 Pro 0813 (TokenRouter)",
		providerPresetId: "tokenrouter",
		category: "latest",
		tags: ["TokenRouter", "DeepSeek", "Reasoning", "Tools"],
		description: "DeepSeek V4 Pro 0813 through TokenRouter's OpenAI-compatible gateway.",
		model: {
			id: "deepseek/deepseek-v4-pro-0813",
			_comment:
				"Quick Setup defaults based on TokenRouter documentation and official DeepSeek V4 Pro-0813 model/thinking docs: https://www.tokenrouter.com/docs, https://api-docs.deepseek.com/quick_start/pricing, and https://api-docs.deepseek.com/guides/thinking_mode",
			displayName: "DeepSeek V4 Pro 0813 (TokenRouter)",
			owned_by: "tokenrouter",
			baseUrl: "https://api.tokenrouter.com/v1",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_tokens: 393216,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "tokenrouter-qwen-3-8-max",
		label: "Qwen3.8-Max (TokenRouter)",
		providerPresetId: "tokenrouter",
		category: "latest",
		tags: ["TokenRouter", "Qwen", "Vision", "Reasoning", "Tools"],
		description: "Qwen3.8-Max through TokenRouter with multimodal input and adjustable reasoning effort.",
		model: {
			id: "qwen/qwen3.8-max",
			_comment:
				"Quick Setup defaults based on TokenRouter documentation and the official Qwen3.8-Max model page: https://www.tokenrouter.com/docs and https://qwen.ai/blog?id=qwen3.8",
			displayName: "Qwen3.8-Max (TokenRouter)",
			owned_by: "tokenrouter",
			baseUrl: "https://api.tokenrouter.com/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1000000,
			max_completion_tokens: 65536,
			reasoning_effort: "xhigh",
			supported_reasoning_efforts: ["low", "medium", "xhigh"],
			default_reasoning_effort: "xhigh",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "tokenrouter-kimi-k3",
		label: "Kimi K3 (TokenRouter)",
		providerPresetId: "tokenrouter",
		category: "latest",
		tags: ["TokenRouter", "Kimi", "Vision", "Reasoning", "Tools"],
		description: "Kimi K3 through TokenRouter with 1M context, vision, tools, and always-on thinking.",
		model: {
			id: "moonshotai/kimi-k3",
			_comment:
				"Quick Setup defaults based on TokenRouter documentation and official Kimi K3 API docs: https://www.tokenrouter.com/docs and https://platform.kimi.ai/docs/guide/kimi-k3-quickstart",
			displayName: "Kimi K3 (TokenRouter)",
			owned_by: "tokenrouter",
			baseUrl: "https://api.tokenrouter.com/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "tokenrouter-glm-5-3",
		label: "GLM-5.3 (TokenRouter)",
		providerPresetId: "tokenrouter",
		category: "latest",
		tags: ["TokenRouter", "Z.AI", "GLM", "Thinking", "Reasoning", "Tools"],
		description: "GLM-5.3 through TokenRouter with forced thinking and preserved reasoning content.",
		model: {
			id: "z-ai/glm-5.3",
			_comment:
				"Quick Setup defaults based on TokenRouter documentation and official Z.AI GLM-5.3/API docs: https://www.tokenrouter.com/docs, https://docs.z.ai/guides/llm/glm-5.3, and https://docs.z.ai/api-reference/llm/chat-completion",
			displayName: "GLM-5.3 (TokenRouter)",
			owned_by: "tokenrouter",
			baseUrl: "https://api.tokenrouter.com/v1",
			apiMode: "openai",
			vision: false,
			context_length: 1000000,
			max_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
				clear_thinking: false,
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "kimi-k2-7-code",
		label: "Kimi K2.7 Code",
		providerPresetId: "kimi",
		category: "latest",
		tags: ["Kimi", "Code", "Vision", "Thinking", "Tools"],
		description: "Kimi's latest code-focused model with multimodal input, tool calling, and always-on thinking.",
		model: {
			id: "kimi-k2.7-code",
			_comment:
				"Quick Setup defaults based on official Kimi K2.7 Code docs: https://platform.kimi.ai/docs/guide/kimi-k2-7-code-quickstart. max_input_tokens is an OAIProxy safety budget to encourage VS Code compaction before Moonshot's 256K provider limit.",
			displayName: "Kimi K2.7 Code",
			owned_by: "kimi",
			baseUrl: "https://api.moonshot.ai/v1",
			apiMode: "openai",
			vision: true,
			context_length: 262144,
			max_input_tokens: 180000,
			max_completion_tokens: 32768,
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "fireworks-deepseek-v4-pro",
		label: "DeepSeek V4 Pro (Fireworks)",
		providerPresetId: "fireworks",
		category: "recommended",
		tags: ["Fireworks", "DeepSeek", "Reasoning", "Tools"],
		description: "DeepSeek V4 Pro through Fireworks serverless inference.",
		model: {
			id: "accounts/fireworks/models/deepseek-v4-pro",
			_comment:
				"Quick Setup defaults based on the official Fireworks model page and prompt caching guide: https://app.fireworks.ai/models/fireworks/deepseek-v4-pro and https://docs.fireworks.ai/guides/prompt-caching",
			displayName: "DeepSeek V4 Pro (Fireworks)",
			owned_by: "fireworks",
			baseUrl: "https://api.fireworks.ai/inference/v1",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_tokens: 131072,
			toolCalling: true,
			include_reasoning_in_request: true,
			prompt_cache: {
				enabled: true,
			},
		},
	},
	{
		id: "fireworks-kimi-k2-7-code",
		label: "Kimi K2.7 Code (Fireworks)",
		providerPresetId: "fireworks",
		category: "latest",
		tags: ["Fireworks", "Kimi", "Code", "Vision", "Reasoning", "Tools"],
		description: "Kimi K2.7 Code through Fireworks serverless inference.",
		model: {
			id: "accounts/fireworks/models/kimi-k2p7-code",
			_comment:
				"Quick Setup defaults based on the official Fireworks model page and prompt caching guide: https://app.fireworks.ai/models/fireworks/kimi-k2p7-code and https://docs.fireworks.ai/guides/prompt-caching",
			displayName: "Kimi K2.7 Code (Fireworks)",
			owned_by: "fireworks",
			baseUrl: "https://api.fireworks.ai/inference/v1",
			apiMode: "openai",
			vision: true,
			context_length: 262144,
			max_tokens: 32768,
			toolCalling: true,
			include_reasoning_in_request: true,
			prompt_cache: {
				enabled: true,
			},
		},
	},
	{
		id: "fireworks-glm-5-2",
		label: "GLM-5.2 (Fireworks)",
		providerPresetId: "fireworks",
		category: "latest",
		tags: ["Fireworks", "GLM", "Coding", "Reasoning", "Tools"],
		description: "GLM-5.2 through Fireworks serverless inference.",
		model: {
			id: "accounts/fireworks/models/glm-5p2",
			_comment:
				"Quick Setup defaults based on the official Fireworks model page, Chat Completions API, and prompt caching guide: https://app.fireworks.ai/models/fireworks/glm-5p2, https://docs.fireworks.ai/api-reference/post-chatcompletions, and https://docs.fireworks.ai/guides/prompt-caching",
			displayName: "GLM-5.2 (Fireworks)",
			owned_by: "fireworks",
			baseUrl: "https://api.fireworks.ai/inference/v1",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_tokens: 131072,
			toolCalling: true,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["none", "high", "max"],
			default_reasoning_effort: "max",
			include_reasoning_in_request: true,
			prompt_cache: {
				enabled: true,
			},
		},
	},
	{
		id: "kimi-k2-6",
		label: "Kimi K2.6",
		providerPresetId: "kimi",
		category: "latest",
		tags: ["Kimi", "Vision", "Thinking"],
		description: "Kimi's general-purpose multimodal model with thinking enabled for agent tasks.",
		model: {
			id: "kimi-k2.6",
			_comment:
				"Quick Setup defaults based on official Kimi API docs: https://platform.kimi.ai/docs/guide/start-using-kimi-api",
			displayName: "Kimi K2.6",
			owned_by: "kimi",
			baseUrl: "https://api.moonshot.ai/v1",
			apiMode: "openai",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			extra: {
				thinking: {
					type: "enabled",
					keep: "all",
				},
			},
		},
	},
	{
		id: "litellm-kimi-k2-6",
		label: "Kimi K2.6 (LiteLLM)",
		providerPresetId: "litellm",
		category: "latest",
		tags: ["LiteLLM", "Kimi", "Vision", "Thinking"],
		description: "Kimi K2.6 through the LiteLLM proxy sample endpoint with thinking enabled.",
		model: {
			id: "Kimi-K2.6",
			_comment:
				"Quick Setup defaults based on official Kimi API docs and LiteLLM extra_body guidance: https://platform.kimi.ai/docs/guide/start-using-kimi-api",
			displayName: "Kimi K2.6 (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			extra_body: {
				thinking: {
					type: "enabled",
					keep: "all",
				},
			},
		},
	},
	{
		id: "litellm-kimi-k3",
		label: "Kimi K3 (LiteLLM)",
		providerPresetId: "litellm",
		category: "latest",
		tags: ["LiteLLM", "Kimi", "Code", "Vision", "Thinking", "Tools", "Prompt Cache"],
		description: "Kimi K3 through the LiteLLM proxy sample endpoint for long-horizon coding and deep reasoning.",
		model: {
			id: "Kimi-K3",
			_comment:
				"Quick Setup defaults based on official Kimi K3 docs: https://platform.kimi.ai/docs/guide/kimi-k3-quickstart. K3 uses a 1M-token context and an official 131,072-token default completion allowance; max_completion_tokens can be raised up to 1,048,576 within the context window.",
			displayName: "Kimi K3 (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["max"],
			default_reasoning_effort: "max",
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "litellm-deepseek-v4-1-flash",
		label: "DeepSeek V4.1 Flash (LiteLLM)",
		providerPresetId: "litellm",
		category: "fast",
		tags: ["LiteLLM", "DeepSeek", "Fast", "Vision", "Reasoning", "Tools"],
		description: "DeepSeek V4.1 Flash through the LiteLLM proxy sample endpoint with vision, thinking, and tools.",
		model: {
			id: "DeepSeek-V4.1-Flash",
			_comment:
				"Quick Setup defaults based on official DeepSeek V4.1 Flash docs: https://api-docs.deepseek.com/quick_start/pricing, https://api-docs.deepseek.com/api/create-chat-completion, https://api-docs.deepseek.com/guides/thinking_mode, and https://api-docs.deepseek.com/guides/vision. Uses the Nube gateway alias DeepSeek-V4.1-Flash with max reasoning and the 384K output limit; prompt caching is provider-managed. Nube probes confirmed automatic tool selection with thinking; named and required tool_choice are rejected while thinking is enabled.",
			displayName: "DeepSeek V4.1 Flash (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: true,
			context_length: 1048576,
			max_tokens: 393216,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			thinking: {
				type: "enabled",
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "litellm-glm-5-3-flash",
		label: "GLM-5.3-Flash (LiteLLM)",
		providerPresetId: "litellm",
		category: "fast",
		tags: ["LiteLLM", "Z.AI", "GLM", "Fast", "Vision", "Thinking", "Tools"],
		description: "GLM-5.3-Flash through the LiteLLM proxy sample endpoint with vision and upstream-default thinking.",
		model: {
			id: "GLM-5.3-Flash",
			_comment:
				"Quick Setup defaults based on official Z.AI GLM-5.3-Flash, vLLM, and Chat Completions docs: https://docs.z.ai/guides/vlm/glm-5.3-flash, https://docs.vllm.ai/projects/ascend/zh-cn/main/tutorials/models/GLM5.3-Flash.html, and https://docs.z.ai/api-reference/llm/chat-completion. Uses the Nube gateway alias GLM-5.3-Flash with upstream-default thinking and max reasoning; do not send an explicit thinking field because the vLLM backend rejects it for named tool calls. Context caching is provider-managed.",
			displayName: "GLM-5.3-Flash (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: true,
			context_length: 1000000,
			max_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			temperature: 1,
			top_p: 0.95,
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "litellm-glm-5-3",
		label: "GLM-5.3 (LiteLLM)",
		providerPresetId: "litellm",
		category: "latest",
		tags: ["LiteLLM", "Z.AI", "GLM", "Coding", "Thinking", "Tools"],
		description: "GLM-5.3 through the LiteLLM proxy sample endpoint with tools and upstream-default thinking.",
		model: {
			id: "GLM-5.3",
			_comment:
				"Quick Setup defaults based on official Z.AI GLM-5.3, vLLM, and Chat Completions docs: https://docs.z.ai/guides/llm/glm-5.3, https://docs.vllm.ai/projects/vllm-ascend-cn/zh-cn/latest/tutorials/models/GLM5.3.html, and https://docs.z.ai/api-reference/llm/chat-completion. Uses the Nube gateway alias GLM-5.3 with upstream-default thinking and max reasoning; do not send an explicit thinking field because the vLLM backend rejects it for named tool calls. Context caching is provider-managed.",
			displayName: "GLM-5.3 (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: false,
			context_length: 1000000,
			max_tokens: 131072,
			reasoning_effort: "max",
			supported_reasoning_efforts: ["low", "high", "max"],
			default_reasoning_effort: "max",
			temperature: 1,
			top_p: 0.95,
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "litellm-qwen3-8-27b",
		label: "Qwen3.8-27B (LiteLLM)",
		providerPresetId: "litellm",
		category: "fast",
		tags: ["LiteLLM", "Qwen", "Fast", "Vision", "Reasoning", "Tools"],
		description:
			"Qwen3.8-27B through the LiteLLM proxy sample endpoint with native 262K context and adjustable reasoning.",
		model: {
			id: "Qwen3.8-27B",
			_comment:
				"Quick Setup defaults based on the official Qwen3.8-27B model card: https://huggingface.co/Qwen/Qwen3.8-27B. Uses the Nube gateway alias Qwen3.8-27B, native 262,144-token context, and a conservative 65,536-token output allowance, not an asserted provider maximum. Thinking and preserved thinking are enabled by the model's defaults; xhigh is the documented default reasoning effort. The optional 1M context extension is not assumed.",
			displayName: "Qwen3.8-27B (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			reasoning_effort: "xhigh",
			supported_reasoning_efforts: ["low", "medium", "xhigh"],
			default_reasoning_effort: "xhigh",
			temperature: 1,
			top_p: 0.95,
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "kimi-k2-5",
		label: "Kimi K2.5",
		providerPresetId: "kimi",
		category: "recommended",
		tags: ["Kimi", "Vision", "Thinking"],
		description: "Cost-conscious Kimi multimodal setup for dialogue and agent tasks.",
		model: {
			id: "kimi-k2.5",
			_comment:
				"Quick Setup defaults based on official Kimi API docs: https://platform.kimi.ai/docs/guide/start-using-kimi-api",
			displayName: "Kimi K2.5",
			owned_by: "kimi",
			baseUrl: "https://api.moonshot.ai/v1",
			apiMode: "openai",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			extra: {
				thinking: {
					type: "enabled",
					keep: "all",
				},
			},
		},
	},
	{
		id: "mimo-v2-6-pro",
		label: "MiMo V2.6 Pro",
		providerPresetId: "mimo",
		category: "latest",
		tags: ["MiMo", "Vision", "Thinking", "Tools"],
		description: "Xiaomi MiMo V2.6 Pro for complex projects, long-horizon agent work, and high-value reasoning.",
		model: {
			id: "mimo-v2.6-pro",
			_comment:
				"Quick Setup defaults based on the official Xiaomi MiMo model summary and OpenAI-compatible API docs: https://mimo.mi.com/docs/en-US/quick-start/summary/model and https://mimo.mi.com/docs/en-US/api/chat/openai-api. MiMo V2.6 Pro supports full-modal understanding, deep thinking, function calling, a 1M-token context window, and up to 128K output tokens.",
			displayName: "MiMo V2.6 Pro",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "mimo-v2-6-flash",
		label: "MiMo V2.6 Flash",
		providerPresetId: "mimo",
		category: "fast",
		tags: ["MiMo", "Fast", "Vision", "Thinking", "Tools"],
		description: "Fast Xiaomi MiMo V2.6 model for frequent calls and large-scale professional workflows.",
		model: {
			id: "mimo-v2.6-flash",
			_comment:
				"Quick Setup defaults based on the official Xiaomi MiMo model summary and OpenAI-compatible API docs: https://mimo.mi.com/docs/en-US/quick-start/summary/model and https://mimo.mi.com/docs/en-US/api/chat/openai-api. MiMo V2.6 Flash supports full-modal understanding, deep thinking, function calling, a 1M-token context window, and up to 128K output tokens.",
			displayName: "MiMo V2.6 Flash",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "mimo-v2-5-pro",
		label: "MiMo V2.5 Pro",
		providerPresetId: "mimo",
		category: "recommended",
		tags: ["MiMo", "Thinking", "Tools"],
		description: "Xiaomi MiMo V2.5 Pro for complex agent, coding, and long-context reasoning.",
		model: {
			id: "mimo-v2.5-pro",
			_comment: "Quick Setup defaults based on official Xiaomi MiMo docs/site: https://mimo.xiaomi.com/",
			displayName: "MiMo V2.5 Pro",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_completion_tokens: 131072,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "mimo-v2-5",
		label: "MiMo V2.5",
		providerPresetId: "mimo",
		category: "latest",
		tags: ["MiMo", "Vision", "Thinking", "Tools"],
		description: "Xiaomi MiMo V2.5 full-modal model for multimodal agent workflows.",
		model: {
			id: "mimo-v2.5",
			_comment: "Quick Setup defaults based on official Xiaomi MiMo docs/site: https://mimo.xiaomi.com/",
			displayName: "MiMo V2.5",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "mimo-v2-flash",
		label: "MiMo V2 Flash",
		providerPresetId: "mimo",
		category: "fast",
		tags: ["MiMo", "Fast", "Thinking", "Tools"],
		description: "Fast Xiaomi MiMo V2 option for lower-cost responses and everyday agent work.",
		model: {
			id: "mimo-v2-flash",
			_comment: "Quick Setup defaults based on official Xiaomi MiMo docs/site: https://mimo.xiaomi.com/",
			displayName: "MiMo V2 Flash",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: false,
			context_length: 262144,
			max_completion_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "minimax-m3-openai",
		label: "MiniMax M3",
		providerPresetId: "minimax",
		category: "recommended",
		tags: ["MiniMax", "OpenAI", "Vision", "Adaptive Thinking"],
		description: "MiniMax M3 through the OpenAI-compatible API.",
		model: {
			id: "MiniMax-M3",
			_comment: "Quick Setup defaults based on official MiniMax API docs: https://www.minimax.io/platform/document",
			displayName: "MiniMax M3",
			owned_by: "minimax",
			baseUrl: "https://api.minimax.io/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1000000,
			max_completion_tokens: 131072,
			thinking: {
				type: "adaptive",
			},
			extra: {
				reasoning_split: true,
			},
			toolCalling: true,
		},
	},
	{
		id: "minimax-m3-anthropic",
		label: "MiniMax M3 (Anthropic)",
		providerPresetId: "minimax-anthropic",
		category: "recommended",
		tags: ["MiniMax", "Anthropic", "Vision", "Adaptive Thinking"],
		description: "MiniMax M3 through MiniMax's Anthropic-compatible API.",
		model: {
			id: "MiniMax-M3",
			_comment: "Quick Setup defaults based on official MiniMax API docs: https://www.minimax.io/platform/document",
			configId: "anthropic",
			displayName: "MiniMax M3 (Anthropic)",
			owned_by: "minimax-anthropic",
			baseUrl: "https://api.minimax.io/anthropic",
			apiMode: "anthropic",
			vision: true,
			context_length: 1000000,
			max_tokens: 131072,
			thinking: {
				type: "adaptive",
			},
			prompt_cache: {
				enabled: true,
				anthropic: {
					enabled: true,
					cache_system: true,
					cache_tools: true,
				},
			},
			toolCalling: true,
		},
	},
	{
		id: "gemini-3-pro-preview",
		label: "Gemini 3 Pro Preview",
		providerPresetId: "gemini",
		category: "latest",
		tags: ["Gemini", "Google", "Vision", "Thinking"],
		description: "Google Gemini's advanced multimodal reasoning model.",
		model: {
			id: "gemini-3-pro-preview",
			_comment:
				"Quick Setup defaults based on official Google Gemini model docs: https://ai.google.dev/gemini-api/docs/models",
			displayName: "Gemini 3 Pro Preview",
			owned_by: "google",
			baseUrl: "https://generativelanguage.googleapis.com",
			apiMode: "gemini",
			family: "gemini-3",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 65536,
			toolCalling: true,
		},
	},
	{
		id: "gemini-3-flash-preview",
		label: "Gemini 3 Flash Preview",
		providerPresetId: "gemini",
		category: "fast",
		tags: ["Gemini", "Google", "Fast", "Vision", "Thinking"],
		description: "Fast Gemini 3 preview setup for high-volume multimodal work.",
		model: {
			id: "gemini-3-flash-preview",
			_comment:
				"Quick Setup defaults based on official Google Gemini model docs: https://ai.google.dev/gemini-api/docs/models",
			displayName: "Gemini 3 Flash Preview",
			owned_by: "google",
			baseUrl: "https://generativelanguage.googleapis.com",
			apiMode: "gemini",
			family: "gemini-3",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 65536,
			toolCalling: true,
		},
	},
	{
		id: "gemini-2-5-flash",
		label: "Gemini 2.5 Flash",
		providerPresetId: "gemini",
		category: "recommended",
		tags: ["Gemini", "Google", "Stable", "Vision", "Thinking"],
		description: "Stable Gemini price-performance model for low-latency agentic tasks.",
		model: {
			id: "gemini-2.5-flash",
			_comment:
				"Quick Setup defaults based on official Google Gemini model docs: https://ai.google.dev/gemini-api/docs/models",
			displayName: "Gemini 2.5 Flash",
			owned_by: "google",
			baseUrl: "https://generativelanguage.googleapis.com",
			apiMode: "gemini",
			family: "gemini-2.5",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 65536,
			toolCalling: true,
		},
	},
];
