import type { HFModelItem } from "./types";

export interface ModelPreset {
	id: string;
	label: string;
	providerPresetId: string;
	category: "latest" | "recommended" | "fast" | "local";
	tags: string[];
	description: string;
	model: HFModelItem;
}

export const MODEL_PRESETS: readonly ModelPreset[] = [
	{
		id: "openai-gpt-5-5-responses",
		label: "GPT-5.5",
		providerPresetId: "openai",
		category: "latest",
		tags: ["OpenAI", "Responses", "Vision", "Reasoning"],
		description: "OpenAI frontier model for complex coding and professional work.",
		model: {
			id: "gpt-5.5",
			displayName: "GPT-5.5",
			owned_by: "openai",
			baseUrl: "https://api.openai.com/v1",
			apiMode: "openai-responses",
			family: "gpt-5.5",
			vision: true,
			context_length: 1050000,
			max_tokens: 128000,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["none", "low", "medium", "high", "xhigh"],
			default_reasoning_effort: "high",
			toolCalling: true,
			extra: {
				reasoning: {
					summary: "detailed",
				},
			},
		},
	},
	{
		id: "openai-gpt-5-5-chat-completions",
		label: "GPT-5.5 (Chat Completions)",
		providerPresetId: "openai",
		category: "recommended",
		tags: ["OpenAI", "Chat Completions", "Vision", "Prompt Cache"],
		description: "OpenAI-compatible Chat Completions setup for GPT-5.5.",
		model: {
			id: "gpt-5.5",
			configId: "chat-completions",
			displayName: "GPT-5.5 (Chat Completions)",
			owned_by: "openai",
			baseUrl: "https://api.openai.com/v1",
			apiMode: "openai",
			family: "gpt-5.5",
			vision: true,
			context_length: 1050000,
			max_completion_tokens: 128000,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["none", "low", "medium", "high", "xhigh"],
			default_reasoning_effort: "high",
			prompt_cache: {
				enabled: true,
			},
			toolCalling: true,
		},
	},
	{
		id: "anthropic-claude-opus-4-7",
		label: "Claude Opus 4.7",
		providerPresetId: "anthropic",
		category: "latest",
		tags: ["Anthropic", "Claude", "Vision", "Adaptive Thinking"],
		description: "Anthropic's high-capability Claude model for complex reasoning and agentic coding.",
		model: {
			id: "claude-opus-4-7",
			displayName: "Claude Opus 4.7",
			owned_by: "anthropic",
			baseUrl: "https://api.anthropic.com",
			apiMode: "anthropic",
			family: "claude-opus-4.7",
			vision: true,
			context_length: 1000000,
			max_tokens: 128000,
			toolCalling: true,
			supports_reasoning_effort: true,
			supported_reasoning_efforts: ["low", "medium", "high", "xhigh", "max"],
			default_reasoning_effort: "high",
			reasoning_effort: "high",
			thinking: {
				type: "adaptive",
			},
			prompt_cache: {
				enabled: true,
				anthropic: {
					enabled: true,
					cache_system: true,
					cache_tools: true,
				},
			},
		},
	},
	{
		id: "anthropic-claude-sonnet-4-6",
		label: "Claude Sonnet 4.6",
		providerPresetId: "anthropic",
		category: "recommended",
		tags: ["Anthropic", "Claude", "Vision", "Adaptive Thinking"],
		description: "Balanced Claude setup for coding, agent workflows, and daily production use.",
		model: {
			id: "claude-sonnet-4-6",
			displayName: "Claude Sonnet 4.6",
			owned_by: "anthropic",
			baseUrl: "https://api.anthropic.com",
			apiMode: "anthropic",
			family: "claude-sonnet-4.6",
			vision: true,
			context_length: 1000000,
			max_tokens: 64000,
			toolCalling: true,
			supports_reasoning_effort: true,
			supported_reasoning_efforts: ["low", "medium", "high", "max"],
			default_reasoning_effort: "medium",
			reasoning_effort: "medium",
			thinking: {
				type: "adaptive",
			},
			prompt_cache: {
				enabled: true,
				anthropic: {
					enabled: true,
					cache_system: true,
					cache_tools: true,
				},
			},
		},
	},
	{
		id: "deepseek-v4-pro",
		label: "DeepSeek V4 Pro",
		providerPresetId: "deepseek",
		category: "recommended",
		tags: ["DeepSeek", "Reasoning", "Tools"],
		description: "DeepSeek V4 Pro with thinking mode enabled for agentic coding workflows.",
		model: {
			id: "deepseek-v4-pro",
			displayName: "DeepSeek V4 Pro",
			owned_by: "deepseek",
			baseUrl: "https://api.deepseek.com",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_tokens: 65536,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["high", "max"],
			default_reasoning_effort: "high",
			thinking: {
				type: "enabled",
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "deepseek-v4-flash",
		label: "DeepSeek V4 Flash",
		providerPresetId: "deepseek",
		category: "fast",
		tags: ["DeepSeek", "Fast", "Reasoning", "Tools"],
		description: "Fast DeepSeek V4 option with the same OpenAI-compatible endpoint.",
		model: {
			id: "deepseek-v4-flash",
			displayName: "DeepSeek V4 Flash",
			owned_by: "deepseek",
			baseUrl: "https://api.deepseek.com",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_tokens: 65536,
			reasoning_effort: "high",
			supported_reasoning_efforts: ["high", "max"],
			default_reasoning_effort: "high",
			thinking: {
				type: "enabled",
			},
			toolCalling: true,
			include_reasoning_in_request: true,
		},
	},
	{
		id: "kimi-k2-6",
		label: "Kimi K2.6",
		providerPresetId: "kimi",
		category: "latest",
		tags: ["Kimi", "Vision", "Thinking"],
		description: "Kimi's latest agentic coding model with multimodal input and thinking enabled.",
		model: {
			id: "kimi-k2.6",
			displayName: "Kimi K2.6",
			owned_by: "kimi",
			baseUrl: "https://api.moonshot.ai/v1",
			apiMode: "openai",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			extra: {
				thinking: {
					type: "enabled",
					keep: "all",
				},
			},
		},
	},
	{
		id: "litellm-kimi-k2-6",
		label: "Kimi K2.6 (LiteLLM)",
		providerPresetId: "litellm",
		category: "latest",
		tags: ["LiteLLM", "Kimi", "Vision", "Thinking"],
		description: "Kimi K2.6 through the LiteLLM proxy sample endpoint with thinking enabled.",
		model: {
			id: "Kimi-K2.6",
			displayName: "Kimi K2.6 (LiteLLM)",
			owned_by: "litellm",
			baseUrl: "https://ai.nube.sh/api/v1",
			apiMode: "litellm",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			extra_body: {
				thinking: {
					type: "enabled",
					keep: "all",
				},
			},
		},
	},
	{
		id: "kimi-k2-5",
		label: "Kimi K2.5",
		providerPresetId: "kimi",
		category: "recommended",
		tags: ["Kimi", "Vision", "Thinking"],
		description: "Cost-conscious Kimi multimodal setup for dialogue and agent tasks.",
		model: {
			id: "kimi-k2.5",
			displayName: "Kimi K2.5",
			owned_by: "kimi",
			baseUrl: "https://api.moonshot.ai/v1",
			apiMode: "openai",
			vision: true,
			context_length: 262144,
			max_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			extra: {
				thinking: {
					type: "enabled",
					keep: "all",
				},
			},
		},
	},
	{
		id: "mimo-v2-5-pro",
		label: "MiMo V2.5 Pro",
		providerPresetId: "mimo",
		category: "recommended",
		tags: ["MiMo", "Thinking", "Tools"],
		description: "Xiaomi MiMo V2.5 Pro for complex agent, coding, and long-context reasoning.",
		model: {
			id: "mimo-v2.5-pro",
			displayName: "MiMo V2.5 Pro",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: false,
			context_length: 1048576,
			max_completion_tokens: 131072,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "mimo-v2-5",
		label: "MiMo V2.5",
		providerPresetId: "mimo",
		category: "latest",
		tags: ["MiMo", "Vision", "Thinking", "Tools"],
		description: "Xiaomi MiMo V2.5 full-modal model for multimodal agent workflows.",
		model: {
			id: "mimo-v2.5",
			displayName: "MiMo V2.5",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 131072,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "mimo-v2-flash",
		label: "MiMo V2 Flash",
		providerPresetId: "mimo",
		category: "fast",
		tags: ["MiMo", "Fast", "Thinking", "Tools"],
		description: "Fast Xiaomi MiMo V2 option for lower-cost responses and everyday agent work.",
		model: {
			id: "mimo-v2-flash",
			displayName: "MiMo V2 Flash",
			owned_by: "mimo",
			baseUrl: "https://api.xiaomimimo.com/v1",
			apiMode: "openai",
			vision: false,
			context_length: 262144,
			max_completion_tokens: 65536,
			thinking: {
				type: "enabled",
			},
			include_reasoning_in_request: true,
			toolCalling: true,
		},
	},
	{
		id: "minimax-m3-openai",
		label: "MiniMax M3",
		providerPresetId: "minimax",
		category: "recommended",
		tags: ["MiniMax", "OpenAI", "Vision", "Adaptive Thinking"],
		description: "MiniMax M3 through the OpenAI-compatible API.",
		model: {
			id: "MiniMax-M3",
			displayName: "MiniMax M3",
			owned_by: "minimax",
			baseUrl: "https://api.minimax.io/v1",
			apiMode: "openai",
			vision: true,
			context_length: 1000000,
			max_completion_tokens: 131072,
			thinking: {
				type: "adaptive",
			},
			extra: {
				reasoning_split: true,
			},
			toolCalling: true,
		},
	},
	{
		id: "minimax-m3-anthropic",
		label: "MiniMax M3 (Anthropic)",
		providerPresetId: "minimax-anthropic",
		category: "recommended",
		tags: ["MiniMax", "Anthropic", "Vision", "Adaptive Thinking"],
		description: "MiniMax M3 through MiniMax's Anthropic-compatible API.",
		model: {
			id: "MiniMax-M3",
			configId: "anthropic",
			displayName: "MiniMax M3 (Anthropic)",
			owned_by: "minimax-anthropic",
			baseUrl: "https://api.minimax.io/anthropic",
			apiMode: "anthropic",
			vision: true,
			context_length: 1000000,
			max_tokens: 131072,
			thinking: {
				type: "adaptive",
			},
			prompt_cache: {
				enabled: true,
				anthropic: {
					enabled: true,
					cache_system: true,
					cache_tools: true,
				},
			},
			toolCalling: true,
		},
	},
	{
		id: "gemini-3-pro-preview",
		label: "Gemini 3 Pro Preview",
		providerPresetId: "gemini",
		category: "latest",
		tags: ["Gemini", "Google", "Vision", "Thinking"],
		description: "Google Gemini's advanced multimodal reasoning model.",
		model: {
			id: "gemini-3-pro-preview",
			displayName: "Gemini 3 Pro Preview",
			owned_by: "google",
			baseUrl: "https://generativelanguage.googleapis.com",
			apiMode: "gemini",
			family: "gemini-3",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 65536,
			toolCalling: true,
		},
	},
	{
		id: "gemini-3-flash-preview",
		label: "Gemini 3 Flash Preview",
		providerPresetId: "gemini",
		category: "fast",
		tags: ["Gemini", "Google", "Fast", "Vision", "Thinking"],
		description: "Fast Gemini 3 preview setup for high-volume multimodal work.",
		model: {
			id: "gemini-3-flash-preview",
			displayName: "Gemini 3 Flash Preview",
			owned_by: "google",
			baseUrl: "https://generativelanguage.googleapis.com",
			apiMode: "gemini",
			family: "gemini-3",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 65536,
			toolCalling: true,
		},
	},
	{
		id: "gemini-2-5-flash",
		label: "Gemini 2.5 Flash",
		providerPresetId: "gemini",
		category: "recommended",
		tags: ["Gemini", "Google", "Stable", "Vision", "Thinking"],
		description: "Stable Gemini price-performance model for low-latency agentic tasks.",
		model: {
			id: "gemini-2.5-flash",
			displayName: "Gemini 2.5 Flash",
			owned_by: "google",
			baseUrl: "https://generativelanguage.googleapis.com",
			apiMode: "gemini",
			family: "gemini-2.5",
			vision: true,
			context_length: 1048576,
			max_completion_tokens: 65536,
			toolCalling: true,
		},
	},
];
